name: rebuild index.html from sources repo

on:
  workflow_dispatch:
    inputs:
      commitMessage:
        description: "Commit message"
        required: true
        default: "autoupdate index.html"
      name:
        description: "Username for commit"
        required: true
        default: "YakovL"
      email:
        description: "User email for commit"
        required: true
        default: ${{ secrets.DEFAULT_COMMITTER_EMAIL }}

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      # should be run first since it makes files created in cwd before not accessible
      - uses: actions/checkout@v2
      - name: get TiddlyWiki source
        run: git clone https://github.com/TiddlyWiki/TiddlyWiki.git
      - name: install and build
        run: |
          cd ./TiddlyWiki
          npm i
          npm run build-site
          cd ..
      - name: move and commit resulting file
        # get the "build/cooked/2.9.2" path bit from core repo itself
        # mv ./TiddlyWiki/build/cooked/2.9.2/index.html ./
        # enrich commit message with event/source commit
        run: |
          mv ./TiddlyWiki/build/cooked/*/index.html ./
          git config --global user.name ${{ github.event.inputs.name }}
          git config --global user.email ${{ github.event.inputs.email }}
          git add ./index.html
          git commit -m "${{ github.event.inputs.commitMessage }}"
          git push