on: push

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: get TiddlyWiki source
        run: git clone https://github.com/TiddlyWiki/TiddlyWiki.git
      - name: install and build
        run: |
          cd ./TiddlyWiki
          npm i
          npm run build-site
          cd ..
          echo 'ls:'
          ls
          echo 'ls ./TiddlyWiki:'
          ls ./TiddlyWiki
      # this is to be fixed:
      - uses: actions/checkout@v2
      - name: move and commit resulting file
        # get the "build/cooked/2.9.2" path bit from core repo itself
        # mv ./TiddlyWiki/build/cooked/2.9.2/index.html ./
        # enrich commit message with event/source commit
        run: |
          echo 'ls:'
          ls
          echo 'ls ./TiddlyWiki:'
          ls ./TiddlyWiki
          mv ./TiddlyWiki/build/cooked/*/index.html ./
          git add ./index.html
          git commit -m "autoupdate index"